name: Deploy HTML Files

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create public directory
        run: mkdir -p gh-pages

      - name: Copy HTML files
        run: |
          cp ./03_spectro_tool/src/spectrochrome.html gh-pages/

      - name: Optional index page
        run: |
          cat > gh-pages/index.html <<EOF
          <html>
          <body>
            <h1>Available Pages</h1>
            <ul>
              <li><a href="spectrochrome.html"><b>SpectroChrome</b></a> - Simple spectogram visualisation for short music sound files</li>
            </ul>
          </body>
          </html>
          EOF

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
